<a href="https://colab.research.google.com/github/DhruvHaritash13/RL1/blob/main/AIML_4EXP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_selection import VarianceThreshold
import numpy as np

# Create a sample dataset
X = np.array([[0, 1, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1]])

# Initialize the VarianceThreshold object
selector = VarianceThreshold(threshold=0.2)

# Fit and transform the data
X_new = selector.fit_transform(X)

print("Original data:")
print(X)
print("After Variance Threshold feature selection:")
print(X_new)



Original data:
[[0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]
After Variance Threshold feature selection:
[[0]
 [1]
 [0]
 [1]]


In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import numpy as np

# Create a sample dataset
X = np.array([[1, 0, 1], [2, 0, 2], [3, 1, 3], [4, 1, 4]])
y = np.array([0, 1, 0, 1])

# Initialize SelectKBest with the chi-squared test
selector = SelectKBest(score_func=chi2, k=2)

# Fit and transform the data
X_new = selector.fit_transform(X, y)

print("Original data:")
print(X)
print("After SelectKBest with Chi-Squared feature selection:")
print(X_new)


Original data:
[[1 0 1]
 [2 0 2]
 [3 1 3]
 [4 1 4]]
After SelectKBest with Chi-Squared feature selection:
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
